title: Flat White Portraits
description: Capturing life's most meaningful moments with a natural, timeless approach.
url: https://www.flatwhiteportraits.com
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - LICENSE
  - CNAME
